# Longer maximum line length
MD013:
  line_length: 160
  code_block_line_length: 120
MD046: { style: fenced }

# Rules covered by prettier
MD003: false
MD004: false
MD005: false
MD006: false
MD007: false
MD009: false
MD010: false
MD012: false
MD019: false
MD022: false
MD023: false
MD027: false
MD029: false
MD030: false
MD031: false
MD032: false
MD035: false
MD047: false
MD048: false
